### ISSUE TITLE
Test failure on signup.

### ISSUE THREAD

**Issue by dajohi** [decred/politeiagui#179]
Seems like valid test failure.

```
 main/signup   
 main/signup   Results for:  Test signup
 main/signup   ✔ Element <.logout.hover a> was visible after 1018 milliseconds.
 main/signup   ✔ Element <.page.logout-page> was visible after 1088 milliseconds.
 main/signup   ✔ Element <.login-required> was visible after 54 milliseconds.
 main/signup   ✔ Element <.login-required> was visible after 42 milliseconds.
 main/signup   ✔ Element <#login> was visible after 93 milliseconds.
 main/signup   ✔ Element <#login> was visible after 37 milliseconds.
 main/signup   ✔ Element <.message-ct.message-error> was visible after 50 milliseconds.
 main/signup   ✔ Element <#login> was visible after 31 milliseconds.
 main/signup   ✔ Element <.message-ct.message-error> was visible after 38 milliseconds.
 main/signup   ✔ Element <#login> was visible after 43 milliseconds.
 main/signup   ✔ Element <.message-ct.message-error> was visible after 33 milliseconds.
 main/signup   ✔ Element <#login> was visible after 32 milliseconds.
 main/signup   ✖ Timed out while waiting for element <#header-bottom-right .user> to be present for 10000 milliseconds.  - expected "visible" but got: "not found"
 main/signup       at Page.signup (/home/travis/build/decred/politeiagui/test/e2e/page_objects/auth.js:84:8)
    at Object.Test signup (/home/travis/build/decred/politeiagui/test/e2e/main/signup.js:22:10)
 main/signup   FAILED:  1 assertions failed and 12 passed (19.466s)
  >> main/signup finished.  
 _________________________________________________
 TEST FAILURE:  1 assertions failed, 49 passed. (42.969s)
 ✖ signup
   - Test signup (19.466s)
   Timed out while waiting for element <#header-bottom-right .user> to be present for 10000 milliseconds.  - expected "visible" but got: "not found"
       at Page.signup (/home/travis/build/decred/politeiagui/test/e2e/page_objects/auth.js:84:8)
       at Object.Test signup (/home/travis/build/decred/politeiagui/test/e2e/main/signup.js:22:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by thi4go** [comment]
Working on this
