### ISSUE TITLE
Clicking on proposals in the admin menu results in error

### ISSUE THREAD

**Issue by marcopeereboom** [decred/politeiagui#263]
![image](https://user-images.githubusercontent.com/4366787/38937158-27e7d93e-42e8-11e8-8ea3-99751c58b7bd.png)
![image](https://user-images.githubusercontent.com/4366787/38937175-347f8e4e-42e8-11e8-85d3-0a1a27f6687a.png)

This means that there is no way to click my way to unvetted proposals.

**Comment by marcopeereboom** [comment]
This is the www result

```
2018-04-18 14:24:12.573 [INF] PWWW: 70.114.160.212 via 10.135.7.135:55618 GET /v1/user/proposals?userid=0 HTTP/1.1
2018-04-18 14:24:12.574 [ERR] PWWW: 70.114.160.212 via 10.135.7.135:55618 GET /v1/user/proposals?userid=0 HTTP/1.1 Internal error 1524061452: handleUserProposals: getSessionUser user not found
2018-04-18 14:24:12.574 [ERR] PWWW: Stacktrace: goroutine 3329 [running]:
runtime/debug.Stack(0xc4201e4060, 0xc420240b40, 0x90)
        /home/marco/go/go/src/runtime/debug/stack.go:24 +0xa7
main.RespondWithError(0xb46a00, 0xc4229bd260, 0xc420672a00, 0x0, 0x9d0013, 0x26, 0xc422161dd0, 0x1, 0x1)
        /home/marco/go/src/github.com/decred/politeia/politeiawww/www.go:219 +0xc9f
main.(*politeiawww).handleUserProposals(0xc4201e4b60, 0xb46a00, 0xc4229bd260, 0xc420672a00)
        /home/marco/go/src/github.com/decred/politeia/politeiawww/www.go:765 +0x3fc
main.(*politeiawww).(main.handleUserProposals)-fm(0xb46a00, 0xc4229bd260, 0xc420672a00)
        /home/marco/go/src/github.com/decred/politeia/politeiawww/www.go:1063 +0x48
main.(*politeiawww).loadInventory.func1(0xb46a00, 0xc4229bd260, 0xc420672a00)
        /home/marco/go/src/github.com/decred/politeia/politeiawww/middleware.go:98 +0x132
main.logging.func1(0xb46a00, 0xc4229bd260, 0xc420672a00)
        /home/marco/go/src/github.com/decred/politeia/politeiawww/middleware.go:78 +0x27d
net/http.HandlerFunc.ServeHTTP(0xc4204e9190, 0xb46a00, 0xc4229bd260, 0xc420672a00)
        /home/marco/go/go/src/net/http/server.go:1947 +0x44
github.com/decred/politeia/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420188c40, 0xb46a00, 0xc4229bd260, 0xc420672a00)
        /home/marco/go/src/github.com/decred/politeia/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/decred/politeia/vendor/github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc420360000, 0xb46a00, 0xc4229bd260, 0xc420672600)
        /home/marco/go/src/github.com/decred/politeia/vendor/github.com/gorilla/csrf/csrf.go:267 +0x323
net/http.serverHandler.ServeHTTP(0xc4204ea000, 0xb46a00, 0xc4229bd260, 0xc420672500)
        /home/marco/go/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420361900, 0xb46e80, 0xc42213e580)
        /home/marco/go/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /home/marco/go/go/src/net/http/server.go:2795 +0x27b
```
